[public]
; === INBOUND ROUTING ===
exten => s,1,NoOp(Connected leg)
same => n,Echo()
same => n,Hangup()
exten => _+1NXXNXXXXXX,1,Dial(PJSIP/sipup-trunk/sip:@sip.sipup.org)
same => n,Hangup()
exten => _1NXXNXXXXXX,1,Dial(PJSIP/sipup-trunk/sip:+1@sip.sipup.org)
same => n,Hangup()
exten => _NXXNXXXXXX,1,Dial(PJSIP/sipup-trunk/sip:+1@sip.sipup.org)
same => n,Hangup()
exten => _NXXXXXX,1,Dial(PJSIP/sipup-trunk/sip:+1780@sip.sipup.org)
same => n,Hangup()
exten => 7001,1,Dial(PJSIP/7001)
same => n,Hangup()
exten => 9196,1,Answer()
same => n,Echo()
same => n,Hangup()

[outbound-calls]
; AMI Originate defaults here — mirror public outbound rules
include => public
