[modules]
autoload=yes
noload => res_stasis.so
noload => res_stasis_answer.so
noload => res_stasis_device_state.so
noload => res_stasis_playback.so
noload => res_stasis_recording.so
noload => res_stasis_snoop.so
noload => res_ari.so
noload => res_ari_applications.so
noload => res_ari_asterisks.so
noload => res_ari_bridges.so
noload => res_ari_channels.so
noload => res_ari_device_states.so
noload => res_ari_endpoints.so
noload => res_ari_events.so
noload => res_ari_mailboxes.so
noload => res_ari_model.so
noload => res_ari_playbacks.so
noload => res_ari_recordings.so
noload => res_ari_sounds.so
